/**
 * Blog API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Privacy } from './privacy';

export interface Blog { 
    id?: string;
    title?: string;
    content?: string;
    createdAt?: Date;
    updatedAt?: Date;
    category?: Category;
    privacy?: Privacy;
    authorId?: string;
    isBlocked?: boolean;
    pathsToImages?: Array<string>;
}